import assert from "node:assert/strict";
import { after, before, test } from "node:test";

/**
 * ISOLATION MULTI-TENANT — Postgres réel in-process (PGlite),
 * zéro Docker : deux utilisateurs distincts ne voient QUE leurs données, même
 * cours, mêmes requêtes SQL. L'isolation est structurelle (schema-per-tenant,
 * search_path) — il n'existe AUCUN moyen pour une requête applicative de lire
 * le schéma d'un autre tenant.
 */

process.env.DB_DRIVER = "postgres";
process.env.DATABASE_URL = "pglite://memory";

import { runWithCourse } from "../db/client";
import { runWithUser, tenantSchema } from "../db/context";
import { q } from "../db/q";
import { toDollarParams } from "../db/driver-postgres";

before(() => {
  delete process.env.CORTEX_USER;
});

after(async () => {
  const { closePostgres } = await import("../db/driver-postgres");
  await closePostgres();
  delete process.env.DB_DRIVER;
  delete process.env.DATABASE_URL;
});

test("toDollarParams : ? → $n, en ignorant les chaînes et identifiants quotés", () => {
  assert.equal(toDollarParams("SELECT * FROM t WHERE a = ? AND b = ?"), "SELECT * FROM t WHERE a = $1 AND b = $2");
  assert.equal(toDollarParams("SELECT '?' q, \"col?\" FROM t WHERE x = ?"), "SELECT '?' q, \"col?\" FROM t WHERE x = $1");
  assert.equal(toDollarParams("SELECT 'l''un ?' FROM t WHERE x = ?"), "SELECT 'l''un ?' FROM t WHERE x = $1");
});

test("tenantSchema : identifiants PG sûrs, lisibles et UNIQUES par utilisateur", () => {
  const alice = runWithUser("alice", () => runWithCourse("cs-202", () => tenantSchema()));
  const bob = runWithUser("Bob-77@x", () => runWithCourse("ml", () => tenantSchema()));
  // Forme : t_<user>_<cours>, caractères sûrs, sous la limite PG de 63.
  for (const s of [alice, bob]) {
    assert.match(s, /^t_[a-z0-9_]+$/, `identifiant PG non sûr : ${s}`);
    assert.ok(s.length < 63, `identifiant PG trop long : ${s}`);
  }
  assert.ok(alice.startsWith("t_alice_") && alice.endsWith("_cs_202"), alice);
  assert.ok(bob.startsWith("t_bob_77_x_") && bob.endsWith("_ml"), bob);
  // Deux comptes dont l'identifiant se TRONQUE au même préfixe doivent avoir
  // des schémas distincts : sinon leurs données fusionnent (le suffixe est un
  // condensé de l'identifiant complet, cf. db/context.ts userSlug).
  const long1 = "utilisateur.tres.long.pour.tronquer@exemple.com";
  const long2 = "utilisateur.tres.long.pour.tronquer@exemple.org";
  const s1 = runWithUser(long1, () => runWithCourse("ml", () => tenantSchema()));
  const s2 = runWithUser(long2, () => runWithCourse("ml", () => tenantSchema()));
  assert.notEqual(s1, s2, "deux comptes distincts partagent le même schéma");
});

test("isolation : alice et bob ne voient QUE leurs données (même cours, même SQL)", async () => {
  await runWithUser("alice", () =>
    runWithCourse("ml", async () => {
      await q.run(`INSERT INTO weaknesses (topic, severity) VALUES (?, ?)`, "gradient descent", 3);
      await q.run(`INSERT INTO weaknesses (topic, severity) VALUES (?, ?)`, "kernels", 2);
    })
  );
  await runWithUser("bob", () =>
    runWithCourse("ml", async () => {
      await q.run(`INSERT INTO weaknesses (topic, severity) VALUES (?, ?)`, "backprop", 1);
    })
  );

  const aliceRows = await runWithUser("alice", () =>
    runWithCourse("ml", () => q.all<{ topic: string }>(`SELECT topic FROM weaknesses ORDER BY topic`))
  );
  const bobRows = await runWithUser("bob", () =>
    runWithCourse("ml", () => q.all<{ topic: string }>(`SELECT topic FROM weaknesses ORDER BY topic`))
  );

  assert.deepEqual(aliceRows.map((r) => r.topic), ["gradient descent", "kernels"]);
  assert.deepEqual(bobRows.map((r) => r.topic), ["backprop"]);
});

test("isolation : les cours d'un même utilisateur sont aussi des tenants séparés", async () => {
  const mlCount = await runWithUser("alice", () =>
    runWithCourse("algo", () => q.get<{ n: number }>(`SELECT count(*) n FROM weaknesses`))
  );
  assert.equal(Number(mlCount!.n), 0);
});

test("q.insert : RETURNING id + identités préservables", async () => {
  const id = await runWithUser("alice", () =>
    runWithCourse("ml", () => q.insert(`INSERT INTO feedback (verdict) VALUES (?)`, "good"))
  );
  assert.ok(id >= 1);
  // insertion avec id EXPLICITE (migration sqlite→pg) : GENERATED BY DEFAULT le permet
  await runWithUser("alice", () =>
    runWithCourse("ml", () => q.run(`INSERT INTO feedback (id, verdict) VALUES (?, ?)`, 999, "too_easy"))
  );
  const got = await runWithUser("alice", () =>
    runWithCourse("ml", () => q.get<{ verdict: string }>(`SELECT verdict FROM feedback WHERE id = ?`, 999))
  );
  assert.equal(got!.verdict, "too_easy");
});

test("q.tx : rollback sur erreur (transaction PG réelle)", async () => {
  await runWithUser("alice", () =>
    runWithCourse("ml", async () => {
      const before = (await q.get<{ n: number }>(`SELECT count(*) n FROM topics`))!.n;
      await assert.rejects(
        q.tx(async () => {
          await q.run(`INSERT INTO topics (label) VALUES (?)`, "tx-topic");
          throw new Error("boom");
        })
      );
      const after = (await q.get<{ n: number }>(`SELECT count(*) n FROM topics`))!.n;
      assert.equal(Number(after), Number(before));
    })
  );
});

test("ensureColumns : no-op quand la colonne existe, ADD sinon (information_schema)", async () => {
  await runWithUser("alice", () =>
    runWithCourse("ml", async () => {
      await q.ensureColumns("topics", ["exo_type", "trap"]); // déjà dans le DDL → no-op
      const cols = await q.columns("topics");
      assert.ok(cols.includes("exo_type") && cols.includes("trap"));
    })
  );
});

test("tenantSchema : les noms des schémas EXISTANTS en prod ne changent pas", () => {
  // Valeurs relevées sur la base de production : tout changement ici
  // orphelinerait les données des tenants (les schémas ne sont pas renommés).
  assert.equal(runWithUser("owner", () => runWithCourse("cs-202", () => tenantSchema())), "t_owner_4c102969_cs_202");
  assert.equal(runWithUser("owner", () => runWithCourse("ml", () => tenantSchema())), "t_owner_4c102969_ml");
  assert.equal(runWithUser("owner", () => runWithCourse("algo", () => tenantSchema())), "t_owner_4c102969_algo");
  // Compte Google (UUID) : préfixe tronqué + condensé, cours court intact.
  const uuid = "11f5d6de-a50f-4cb1-8d7e-6b2f0c9a1e33";
  const s = runWithUser(uuid, () => runWithCourse("cs-202", () => tenantSchema()));
  assert.match(s, /^t_u11f5d6de_a50f_4cb1_[0-9a-f]{8}_cs_202$/, s);
  assert.equal(s, "t_u11f5d6de_a50f_4cb1_6a9b4745_cs_202");
});

test("tenantSchema : deux cours LONGS d'un même compte ne partagent pas de schéma", () => {
  const c1 = "analyse-des-systemes-lineaires-partie-1";
  const c2 = "analyse-des-systemes-lineaires-partie-2";
  const s1 = runWithUser("alice", () => runWithCourse(c1, () => tenantSchema()));
  const s2 = runWithUser("alice", () => runWithCourse(c2, () => tenantSchema()));
  assert.notEqual(s1, s2, `collision de tenant : ${s1}`);
  for (const s of [s1, s2]) {
    assert.match(s, /^t_[a-z0-9_]+$/, s);
    assert.ok(s.length < 63, s);
  }
});
