/**
 * SOURCE DE VÉRITÉ du schéma applicatif — Phase B backend-overhaul.
 *
 * Historiquement le schéma vivait en 3 endroits divergents : db/schema.ts
 * (Drizzle, 6 tables), db/migrations/0000_*.sql (les mêmes 6) et ~15 tables
 * « lazy » (CREATE TABLE IF NOT EXISTS + ALTER au fil de l'eau dans lib/*).
 * Ce module unifie TOUT en une spec neutre, et génère le DDL des deux dialectes :
 *  - SQLite : identique octet pour octet aux formes historiques fusionnées
 *    (défauts datetime('now'), AUTOINCREMENT…) — appliqué en IF NOT EXISTS,
 *    donc no-op sur les DB existantes (règle d'or : le schéma de cs-202 n'est
 *    jamais modifié au démarrage ; les ensures restent LAZY, aux mêmes points).
 *  - Postgres : types équivalents (integer identity, double precision) avec
 *    timestamps TEXT au MÊME format UTC que SQLite ('YYYY-MM-DD HH24:MI:SS')
 *    et JSON en TEXT — choix délibéré : parité de comportement avec le SQL brut
 *    existant AVANT optimisation PG-native (jsonb/timestamptz viendront après).
 *
 * `GENERATED BY DEFAULT AS IDENTITY` (pas ALWAYS) : la migration SQLite→PG
 * importe les ids historiques tels quels, puis restaure la séquence.
 */

export type ColType = "int" | "real" | "text";

export type Col = {
  name: string;
  type: ColType;
  pk?: boolean;
  /** AUTOINCREMENT (implique pk int). */
  ai?: boolean;
  nn?: boolean;
  /** Défaut : nombre, chaîne SQL déjà quotée, ou "NOW" (timestamp courant UTC). */
  def?: number | string;
  unique?: boolean;
  fk?: { table: string; col: string; onDelete?: "cascade" };
};

export type TableSpec = {
  name: string;
  cols: Col[];
  uniqueIndexes?: { name: string; cols: string[] }[];
};

const now = "NOW" as const;

/** Les 20 tables applicatives (hors fts_items, virtuelle/dialecte — cf. search). */
export const TABLES: TableSpec[] = [
  {
    name: "sources",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "type", type: "text", nn: true },
      { name: "title", type: "text", nn: true },
      { name: "path", type: "text", nn: true },
      { name: "year", type: "int" },
      { name: "recency_weight", type: "real", nn: true, def: 1 },
      { name: "ingested_at", type: "text", def: now },
    ],
  },
  {
    name: "items",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "source_id", type: "int", fk: { table: "sources", col: "id" } },
      { name: "type", type: "text", nn: true },
      { name: "lecture_id", type: "text" },
      { name: "title", type: "text" },
      { name: "text", type: "text", nn: true },
      { name: "html", type: "text" },
      { name: "images", type: "text" },
      { name: "tags", type: "text" },
      { name: "anchor", type: "text" },
      // Ombre normalisée (minuscules sans accents) du texte — UNIQUEMENT alimentée
      // en mode postgres (recherche tsvector accent-insensible). SQLite : FTS5
      // remove_diacritics fait ce travail → colonne jamais écrite (dialecte gaté).
      { name: "text_norm", type: "text" },
    ],
  },
  {
    name: "weaknesses",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "topic", type: "text", nn: true },
      { name: "description", type: "text" },
      { name: "screenshot_path", type: "text" },
      { name: "severity", type: "int", nn: true, def: 2 },
      { name: "related_item_ids", type: "text" },
      { name: "times_seen", type: "int", nn: true, def: 1 },
      { name: "logged_at", type: "text", def: now },
      { name: "last_reviewed_at", type: "text" },
      // Colonnes historiquement ajoutées par ALTER (lib/weaknesses.ts).
      { name: "analyzed", type: "int", nn: true, def: 0 },
      { name: "source", type: "text", nn: true, def: "'manual'" },
      { name: "theme", type: "text" },
    ],
  },
  {
    name: "schedule",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "concept", type: "text", nn: true },
      { name: "last_tested_at", type: "text" },
      { name: "interval_days", type: "int", nn: true, def: 1 },
      { name: "next_due_at", type: "text" },
      { name: "ease", type: "real", nn: true, def: 2.5 },
    ],
    uniqueIndexes: [{ name: "schedule_concept_unique", cols: ["concept"] }],
  },
  {
    name: "exams",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "created_at", type: "text", def: now },
      { name: "format_template", type: "text" },
      { name: "targeted_weakness_ids", type: "text" },
      { name: "html_path", type: "text" },
      { name: "status", type: "text", nn: true, def: "'draft'" },
      { name: "verify_summary", type: "text" }, // ALTER historique (lib/exam.ts, lib/qcm.ts)
    ],
  },
  {
    name: "exam_questions",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "exam_id", type: "int", fk: { table: "exams", col: "id" } },
      { name: "concept", type: "text", nn: true },
      { name: "statement_html", type: "text", nn: true },
      { name: "solution_html", type: "text" },
      { name: "source_inspiration", type: "text" },
      { name: "weakness_id", type: "int", fk: { table: "weaknesses", col: "id" } },
      // ALTER historiques (lib/exam.ts:270-273)
      { name: "verified", type: "int" },
      { name: "verify_issue", type: "text" },
      { name: "verify_method", type: "text" },
    ],
  },
  {
    name: "feedback",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "exam_id", type: "int" },
      { name: "topic", type: "text" },
      { name: "archetype", type: "text" },
      { name: "verdict", type: "text", nn: true },
      { name: "note", type: "text" },
      { name: "score", type: "int" },
      { name: "created_at", type: "text", def: now },
    ],
  },
  {
    name: "eval_items",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "source_exam", type: "text" },
      { name: "exam_page", type: "int" },
      { name: "question_text", type: "text", nn: true },
      { name: "official_answer", type: "text", nn: true },
      { name: "answer_type", type: "text", nn: true },
      { name: "points", type: "real" },
      { name: "topic", type: "text" },
      { name: "options", type: "text" }, // ALTER historique (lib/eval.ts:39)
      { name: "created_at", type: "text", def: now },
    ],
  },
  {
    name: "eval_attempts",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "item_id", type: "int", nn: true },
      { name: "solution", type: "text" },
      { name: "final_answer", type: "text" },
      { name: "verdict", type: "text" },
      { name: "reason", type: "text" },
      { name: "judged_by", type: "text" },
      { name: "created_at", type: "text", def: now },
    ],
  },
  {
    name: "eval_runs",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "course", type: "text" },
      { name: "created_at", type: "text", def: now },
      { name: "model", type: "text" },
      { name: "prompt_version", type: "text" },
      { name: "n_items", type: "int" },
      { name: "accuracy", type: "real" },
      { name: "uncertain_rate", type: "real" },
      { name: "discrimination", type: "real" },
      { name: "style_score", type: "real" },
      { name: "notes", type: "text" },
      { name: "deterministic_rate", type: "real" }, // ALTER historique (lib/eval.ts:65)
    ],
  },
  {
    name: "bank_questions",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "kind", type: "text", nn: true },
      { name: "topic", type: "text", nn: true },
      { name: "subtopic", type: "text" },
      { name: "statement", type: "text", nn: true },
      { name: "official_answer", type: "text" },
      { name: "options", type: "text" },
      { name: "source_exam", type: "text" },
      { name: "exam_year", type: "int" },
      { name: "exam_page", type: "int" },
      { name: "points", type: "real" },
      { name: "lecture_rank", type: "int" },
      { name: "exam_href", type: "text" },
      { name: "created_at", type: "text", def: now },
    ],
  },
  {
    name: "revision_plan",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "kind", type: "text", nn: true },
      { name: "topic", type: "text", nn: true },
      { name: "lecture_rank", type: "int" },
      { name: "statement", type: "text" },
      { name: "options", type: "text" },
      { name: "correct", type: "text" },
      { name: "misconceptions", type: "text" },
      { name: "explanation", type: "text" },
      { name: "solution", type: "text" },
      { name: "verified", type: "int" },
      { name: "verify_method", type: "text" },
      { name: "created_at", type: "text", def: now },
    ],
  },
  {
    name: "topics",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "label", type: "text", nn: true, unique: true },
      { name: "method", type: "text" },
      { name: "category", type: "text" },
      { name: "archetype", type: "text" },
      { name: "exam_weight", type: "real", nn: true, def: 0 },
      { name: "exam_count", type: "int", nn: true, def: 0 },
      { name: "source", type: "text" },
      { name: "description", type: "text" },
      { name: "created_at", type: "text", def: now },
      // ALTER historiques (lib/program.ts:73-74)
      { name: "exo_type", type: "text" },
      { name: "trap", type: "text" },
    ],
  },
  {
    name: "mastery",
    cols: [
      { name: "topic_id", type: "int", pk: true, fk: { table: "topics", col: "id", onDelete: "cascade" } },
      { name: "score", type: "real" },
      { name: "attempts", type: "int", nn: true, def: 0 },
      { name: "last_score", type: "int" },
      { name: "last_done_at", type: "text" },
      { name: "due_at", type: "text" },
      { name: "ease", type: "real", nn: true, def: 2.5 },
      { name: "interval_days", type: "int", nn: true, def: 0 },
      { name: "last_exam_id", type: "int" },
    ],
  },
  {
    name: "jobs",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "type", type: "text", nn: true },
      { name: "target", type: "text" },
      { name: "status", type: "text", nn: true, def: "'queued'" },
      { name: "current_step", type: "text" },
      { name: "progress", type: "int", nn: true, def: 0 },
      { name: "result_path", type: "text" },
      { name: "result_id", type: "int" },
      { name: "error", type: "text" },
      { name: "log_json", type: "text", nn: true, def: "'[]'" },
      { name: "pid", type: "int" },
      { name: "created_at", type: "text", def: now },
      { name: "updated_at", type: "text", def: now },
      // Durabilité (Phase C) : reprise automatique bornée + progression par unité.
      { name: "attempts", type: "int", nn: true, def: 0 },
      { name: "max_attempts", type: "int", nn: true, def: 2 },
      { name: "heartbeat_at", type: "text" },
      { name: "checkpoint_json", type: "text" },
      { name: "worker_id", type: "text" },
    ],
  },
  {
    name: "exam_refs",
    cols: [
      { name: "path", type: "text", pk: true },
      { name: "title", type: "text" },
      { name: "year", type: "int" },
      { name: "kind", type: "text" },
      { name: "uploaded", type: "int", nn: true, def: 0 },
      { name: "added_at", type: "text", def: now },
    ],
  },
  {
    name: "format_profile",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "json", type: "text", nn: true },
      { name: "created_at", type: "text", def: now },
    ],
  },
  {
    name: "exam_exercises",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "exam_title", type: "text" },
      { name: "exam_year", type: "int" },
      { name: "exam_page", type: "int" },
      { name: "topic", type: "text", nn: true },
      { name: "method", type: "text" },
      { name: "exo_type", type: "text" },
      { name: "trap", type: "text" },
      { name: "archetype", type: "text" },
      { name: "statement", type: "text" },
      { name: "points", type: "real" },
      { name: "exam_href", type: "text" },
      { name: "course_href", type: "text" },
      { name: "topic_id", type: "int" },
      { name: "created_at", type: "text", def: now },
    ],
  },
  {
    name: "qcm_items",
    cols: [
      { name: "id", type: "int", pk: true, ai: true },
      { name: "exam_id", type: "int", nn: true },
      { name: "idx", type: "int", nn: true },
      { name: "topic", type: "text" },
      { name: "type", type: "text" },
      { name: "stem", type: "text" },
      { name: "options_json", type: "text" },
      { name: "correct_json", type: "text" },
      { name: "misconceptions_json", type: "text" },
      { name: "explanation", type: "text" },
      { name: "verified", type: "int" },
    ],
  },
  {
    name: "vocab",
    cols: [
      { name: "term", type: "text", pk: true },
      { name: "df", type: "int", nn: true },
    ],
  },
];

export type Dialect = "sqlite" | "postgres";

const PG_NOW_DEFAULT = "to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')";

function colType(c: Col, dialect: Dialect): string {
  if (dialect === "sqlite") return c.type === "int" ? "INTEGER" : c.type === "real" ? "REAL" : "TEXT";
  return c.type === "int" ? "integer" : c.type === "real" ? "double precision" : "text";
}

function colDdl(c: Col, dialect: Dialect): string {
  const parts: string[] = [c.name, colType(c, dialect)];
  if (c.pk) {
    if (c.ai) {
      parts.push(dialect === "sqlite" ? "PRIMARY KEY AUTOINCREMENT" : "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
    } else {
      parts.push("PRIMARY KEY");
    }
  }
  if (c.nn && !c.pk) parts.push("NOT NULL");
  if (c.def !== undefined) {
    const def = c.def === "NOW" ? (dialect === "sqlite" ? "(datetime('now'))" : `(${PG_NOW_DEFAULT})`) : String(c.def);
    parts.push(`DEFAULT ${def}`);
  }
  if (c.unique) parts.push("UNIQUE");
  return parts.join(" ");
}

/** DDL idempotent (CREATE TABLE IF NOT EXISTS + index uniques) d'une table. */
export function tableDdl(spec: TableSpec, dialect: Dialect): string[] {
  const cols = spec.cols.map((c) => colDdl(c, dialect));
  const fks = spec.cols
    .filter((c) => c.fk)
    .map((c) => `FOREIGN KEY (${c.name}) REFERENCES ${c.fk!.table}(${c.fk!.col})${c.fk!.onDelete === "cascade" ? " ON DELETE CASCADE" : ""}`);
  const stmts = [`CREATE TABLE IF NOT EXISTS ${spec.name} (\n  ${[...cols, ...fks].join(",\n  ")}\n)`];
  for (const idx of spec.uniqueIndexes ?? []) {
    stmts.push(`CREATE UNIQUE INDEX IF NOT EXISTS ${idx.name} ON ${spec.name} (${idx.cols.join(", ")})`);
  }
  return stmts;
}

export function getTable(name: string): TableSpec {
  const t = TABLES.find((t) => t.name === name);
  if (!t) throw new Error(`Table inconnue dans db/tables.ts : ${name}`);
  return t;
}

/** DDL d'une table nommée (raccourci des ensures lazy). */
export function ddl(name: string, dialect: Dialect): string[] {
  return tableDdl(getTable(name), dialect);
}

/** DDL complet du schéma applicatif (ordre = TABLES, respecte les FK). */
export function allDdl(dialect: Dialect): string[] {
  return TABLES.flatMap((t) => tableDdl(t, dialect));
}
